volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=guessword
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  server:
    image:server_react
  myapp:
    image: client_react