volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=guessword
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  server_react:
    build : ./server/
    ports:
      - 9000:9000
  auth:
    build : ./auth/
    ports:
      - 8000:8000
  database:
    build : ./database/
    ports:
      - 4000:4000
  auth_client:
    build : ./auth_client/
    ports:
      - 3000:3001
  
  myapp:
    build : ./client/
    ports:
      - 3000:3000